language: ruby
rvm: 2.6.2
install:
  - tool/jt.rb install jvmci
  - tool/jt.rb mx version
  - git clone --depth 1 https://github.com/oracle/graal.git ../graal
  - git -C ../graal fetch --shallow-since=05/11/2019
  - tool/jt.rb mx sforceimports
  - tool/jt.rb build
  - gem install rubocop:0.66.0
script:
  - tool/jt.rb lint
cache:
  directories:
    - $HOME/.mx/cache
