language: ruby
rvm: 2.6.2
install:
  - tool/jt.rb install jvmci
  - tool/jt.rb mx version
  - mkdir ../graal
  - curl -L https://github.com/oracle/graal/archive/aee967f1d90e1f032b266c62d10fc8c32a805fb8.tar.gz | tar xz -C ../graal --strip-components=1
  - tool/jt.rb build --no-sforceimports
  - gem install rubocop:0.66.0
script:
  - tool/jt.rb lint
cache:
  directories:
    - $HOME/.mx/cache
